# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0003_auto_20170721_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='county',
        ),
    ]
