# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0006_accountinfo_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='company_name',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
