# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0007_auto_20170722_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_banner',
            field=models.ImageField(null=True, upload_to='images/banners'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
