# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0008_auto_20170722_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, null=True)),
                ('company_banner', models.ImageField(null=True, upload_to='images/banners')),
                ('account_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_banner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
