# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0009_auto_20170722_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
