# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0011_auto_20170723_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='account_id',
            new_name='account',
        ),
    ]
