# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0015_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
    ]
