# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0016_auto_20170726_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Product'),
        ),
    ]
