# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0017_auto_20170726_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_info',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
