# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0020_auto_20170726_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='D', max_length=2),
        ),
    ]
