# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelogins', '0021_auto_20170727_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='', max_length=2),
        ),
    ]
