# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('product_info', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
