# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
