# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userid',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
