# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(choices=[('Frames', 'Frames'), ('Artwork', 'Artwork')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
