# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170720_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='range',
            field=models.CharField(choices=[('Frames', 'Frames'), ('Artwork', 'Artwork'), ('Furniture', 'Furniture'), ('Upcycled', 'Upcycled')], max_length=15, null=True),
        ),
    ]
