# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170721_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(choices=[('Frames', 'Frames'), ('Artwork', 'Artwork'), ('Furniture', 'Furniture'), ('Upcycled', 'Upcycled')], max_length=15, null=True)),
            ],
        ),
    ]
