# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_banner',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
