# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170722_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='range',
            field=models.CharField(choices=[('frames', 'Frames'), ('artwork', 'Artwork'), ('furniture', 'Furniture'), ('upcycled', 'Upcycled')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='range',
            field=models.CharField(choices=[('frames', 'Frames'), ('artwork', 'Artwork'), ('furniture', 'Furniture'), ('upcycled', 'Upcycled')], max_length=15, null=True),
        ),
    ]
