# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170725_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
