# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 21:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170726_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
