# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170727_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
